#!/bin/sh -xe

exec 2>&1

#
# I found that there was an error when running the application when it came to
# the language. By default it stated that the code was going to run in ASCII
# and I think that one of the libraries had an issue with that. When I started
# searching I came across this as a solution.
export LC_ALL={{cfg.lang}}
export LANG={{cfg.lang}}

#
# Define the application environment variable. Right now this entry point is
# specified in the defaults.toml.

export FLASK_APP={{cfg.app.instance}}

#
# Time to start the application. This is where the pathing does not very
# intuitive. The app is inside the data path. But the libraries and binaries
# are still within the package but with no binaries on the path I have this
# bizarre path where things were vendored.

cd {{pkg.svc_data_path}}/app
exec {{pkg.path}}/app/bin/flask run -p {{cfg.app.port}}
